services:
    simpleweb.stripe.event_listeners.webhook_listener:
        class: Simpleweb\StripeBundle\EventListener\WebhookListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - @fos_user.user_manager
